// @license
// Copyright (c) 2019 - 2025 Dr. Gabriel Gatzsche. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:convert';
import 'dart:io';

// ignore: lines_longer_than_80_chars
import 'package:gg_local_package_dependencies/gg_local_package_dependencies.dart';
import 'package:mocktail/mocktail.dart';
import 'package:path/path.dart' as path;
import 'package:pub_semver/pub_semver.dart';
import 'package:pubspec_parse/pubspec_parse.dart';

import 'git_snapshot.dart';

/// Default process runner that uses the system's `Process.run`
// coverage:ignore-start
Future<ProcessResult> _defaultProcessRunner(
  String executable,
  List<String> arguments, {
  String? workingDirectory,
  Map<String, String>? environment,
}) =>
    Process.run(
      executable,
      arguments,
      workingDirectory: workingDirectory,
      environment: environment,
      runInShell: true,
    );
// coverage:ignore-end

/// The outcome of [PublishSkipCheck.get] for one ticket repository.
class PublishSkipDecision {
  /// Constructor.
  const PublishSkipDecision({required this.skip, required this.reason});

  /// Whether publishing the repository can be skipped.
  final bool skip;

  /// Why the repository can be skipped ([skip] is true) or why it has to be
  /// published ([skip] is false).
  final String reason;
}

/// Decides whether a ticket repository needs to be published at all.
///
/// Many repositories are only part of a ticket because they sit between two
/// changed packages in the dependency chain. Such a pass-through repository
/// does not need a release when
///
/// 1. no dependency published earlier in the run received a version its
///    already-published constraint cannot absorb (i.e. no breaking bump —
///    for versions >= 1.0.0 that is a whole-number/major increase, for 0.x
///    versions the minor position acts as the breaking one), and
/// 2. the repository carries no manual changes — every commit the feature
///    branch adds on top of `origin/main` was generated by gg itself and the
///    working tree is clean.
///
/// Every situation that cannot be judged reliably (unknown dependency
/// version, unparsable constraint, missing git history, …) results in
/// »publish« — skipping is only ever chosen when it is provably safe.
class PublishSkipCheck {
  /// Constructor.
  PublishSkipCheck({ProcessRunner? processRunner})
      : _processRunner = processRunner ?? _defaultProcessRunner;

  /// Runs the git commands used to inspect the repository history.
  final ProcessRunner _processRunner;

  /// Commit subjects gg's ticket tooling creates on a feature branch. Only
  /// these exact subjects are treated as generated — everything else counts
  /// as a manual change, so unclassifiable commits are never lost by a skip.
  static const Set<String> ggGeneratedCommitMessages = {
    'gg_multi: changed references to path',
    'gg_multi: changed references to git',
    'Gg Multi: changed references to pub.dev',
  };

  // ...........................................................................
  /// Returns the skip decision for [repo].
  ///
  /// [refVersions] maps the package names of the repositories processed
  /// earlier in this run to the version they now have (published repos carry
  /// their fresh version, skipped repos their unchanged one).
  Future<PublishSkipDecision> get({
    required Node repo,
    required Map<String, String> refVersions,
  }) async {
    final dependencyReason = _dependencyPublishReason(repo, refVersions);
    if (dependencyReason != null) {
      return PublishSkipDecision(skip: false, reason: dependencyReason);
    }

    final manualChangeReason = await _manualChangeReason(repo.directory);
    if (manualChangeReason != null) {
      return PublishSkipDecision(skip: false, reason: manualChangeReason);
    }

    return const PublishSkipDecision(
      skip: true,
      reason: 'no dependency needs a constraint update '
          'and there are no manual changes',
    );
  }

  // ######################
  // Private
  // ######################

  // ...........................................................................
  /// Returns why a dependency forces a publish of [repo], or null when every
  /// dependency's new version is still covered by the constraint the
  /// repository publishes.
  String? _dependencyPublishReason(
    Node repo,
    Map<String, String> refVersions,
  ) {
    final regularDeps = _regularDependencyNames(repo.directory);
    final constraints = _declaredConstraints(repo.directory, regularDeps);

    for (final dep in repo.dependencies.values) {
      final names = <String>{dep.name, ...dep.aliases};
      final declaredNames = names.intersection(regularDeps);
      if (declaredNames.isEmpty) {
        // A dev-only dependency is invisible to consumers of the published
        // package, so its version never forces a release.
        continue;
      }

      final newVersionString = _newVersionOf(dep, refVersions);
      if (newVersionString == null) {
        return 'the version of dependency »${dep.name}« is unknown';
      }

      final Version newVersion;
      try {
        newVersion = Version.parse(newVersionString);
      } on FormatException {
        return 'the version »$newVersionString« of dependency '
            '»${dep.name}« is not a valid semver version';
      }

      for (final name in declaredNames) {
        final constraint = constraints[name];
        if (constraint == null) {
          return 'no version constraint for dependency »$name« '
              'could be determined';
        }
        if (!constraint.allows(newVersion)) {
          return 'dependency »$name« moved to $newVersion which is '
              'outside the published constraint »$constraint«';
        }
      }
    }

    return null;
  }

  // ...........................................................................
  /// Returns the new version of [dep] captured earlier in the run, looked up
  /// under any of its names (Dart name, npm name, directory name).
  String? _newVersionOf(Node dep, Map<String, String> refVersions) {
    for (final name in <String>{dep.name, ...dep.aliases}) {
      final version = refVersions[name];
      if (version != null) {
        return version;
      }
    }
    return null;
  }

  // ...........................................................................
  /// The names of the *regular* dependencies of the repo in [repoDir] —
  /// `dependencies` of pubspec.yaml plus `dependencies` of package.json.
  /// Dev dependencies are excluded on purpose: registries ignore them when
  /// resolving consumers of the published package.
  Set<String> _regularDependencyNames(Directory repoDir) {
    final result = <String>{};

    final pubspec = _parsedPubspec(repoDir);
    if (pubspec != null) {
      result.addAll(pubspec.dependencies.keys);
    }

    final packageJson = _parsedPackageJson(repoDir);
    final npmDeps = packageJson?['dependencies'];
    if (npmDeps is Map<String, dynamic>) {
      result.addAll(npmDeps.keys);
    }

    return result;
  }

  // ...........................................................................
  /// The version constraints [repoDir] publishes for [names].
  ///
  /// The specs backed up by gg_localize_refs are authoritative — they hold
  /// the original refs while the manifest may be localized to path/git refs.
  /// Names without a backup entry fall back to the constraint currently
  /// declared in the manifest. A null value means the constraint could not
  /// be determined.
  Map<String, VersionConstraint?> _declaredConstraints(
    Directory repoDir,
    Set<String> names,
  ) {
    final manifest = _manifestConstraints(repoDir);
    final saved = _savedDependencySpecs(repoDir);

    final result = <String, VersionConstraint?>{};
    for (final name in names) {
      if (saved.containsKey(name)) {
        result[name] = _constraintFromSpec(saved[name]);
      } else {
        result[name] = manifest[name];
      }
    }
    return result;
  }

  // ...........................................................................
  /// The version constraints currently declared in the manifests of
  /// [repoDir]. Localized refs (path/git) yield no entry.
  Map<String, VersionConstraint> _manifestConstraints(Directory repoDir) {
    final result = <String, VersionConstraint>{};

    final pubspec = _parsedPubspec(repoDir);
    if (pubspec != null) {
      for (final entry in pubspec.dependencies.entries) {
        final dependency = entry.value;
        if (dependency is HostedDependency) {
          result[entry.key] = dependency.version;
        }
      }
    }

    final packageJson = _parsedPackageJson(repoDir);
    final npmDeps = packageJson?['dependencies'];
    if (npmDeps is Map<String, dynamic>) {
      for (final entry in npmDeps.entries) {
        final constraint = _tryParseConstraint(entry.value?.toString());
        if (constraint != null) {
          result[entry.key] = constraint;
        }
      }
    }

    return result;
  }

  // ...........................................................................
  /// The original dependency specs gg_localize_refs backed up before
  /// localizing the refs of [repoDir], merged over the TypeScript/legacy
  /// location (repo root) and the Dart location (`.gg/`).
  Map<String, dynamic> _savedDependencySpecs(Directory repoDir) {
    final result = <String, dynamic>{};
    final files = [
      File(path.join(repoDir.path, '.gg_localize_refs_backup.json')),
      File(path.join(repoDir.path, '.gg', '.gg_localize_refs_backup.json')),
    ];
    for (final file in files) {
      if (!file.existsSync()) {
        continue;
      }
      try {
        final decoded = jsonDecode(file.readAsStringSync());
        if (decoded is Map<String, dynamic>) {
          result.addAll(decoded);
        }
      } catch (_) {
        // An unreadable backup contributes nothing; affected dependencies
        // stay undetermined which makes the decision fall back to publish.
      }
    }
    return result;
  }

  // ...........................................................................
  /// Extracts the version constraint from a backed-up dependency [spec] —
  /// either a plain string (`^1.2.3`) or a map carrying a `version` key
  /// (git dependencies). Returns null when there is none or it is unparsable.
  VersionConstraint? _constraintFromSpec(dynamic spec) {
    if (spec is String) {
      return _tryParseConstraint(spec);
    }
    if (spec is Map) {
      final version = spec['version'];
      if (version != null) {
        return _tryParseConstraint(version.toString());
      }
    }
    return null;
  }

  // ...........................................................................
  /// Parses [raw] as version constraint, returning null when it is not one.
  VersionConstraint? _tryParseConstraint(String? raw) {
    if (raw == null || raw.trim().isEmpty) {
      return null;
    }
    try {
      return VersionConstraint.parse(raw.trim());
    } on FormatException {
      return null;
    }
  }

  // ...........................................................................
  /// The parsed pubspec.yaml of [repoDir], or null when absent/unparsable.
  Pubspec? _parsedPubspec(Directory repoDir) {
    final file = File(path.join(repoDir.path, 'pubspec.yaml'));
    if (!file.existsSync()) {
      return null;
    }
    try {
      return Pubspec.parse(file.readAsStringSync());
    } catch (_) {
      return null;
    }
  }

  // ...........................................................................
  /// The parsed package.json of [repoDir], or null when absent/unparsable.
  Map<String, dynamic>? _parsedPackageJson(Directory repoDir) {
    final file = File(path.join(repoDir.path, 'package.json'));
    if (!file.existsSync()) {
      return null;
    }
    try {
      final decoded = jsonDecode(file.readAsStringSync());
      return decoded is Map<String, dynamic> ? decoded : null;
    } catch (_) {
      return null;
    }
  }

  // ...........................................................................
  /// Returns why [repoDir] contains manual changes, or null when everything
  /// on top of the main branch was generated by gg.
  Future<String?> _manualChangeReason(Directory repoDir) async {
    try {
      final status = await _runGit(
        <String>['status', '--porcelain'],
        repoDir: repoDir,
      );
      if (status.isNotEmpty) {
        return 'the working tree has uncommitted changes';
      }

      final base = await _compareBase(repoDir);
      if (base == null) {
        return 'no main branch to compare against was found';
      }

      final subjects = await _runGit(
        <String>['log', '--no-merges', '--format=%s', '$base..HEAD'],
        repoDir: repoDir,
      );

      for (final line in subjects.split('\n')) {
        final subject = line.trim();
        if (subject.isEmpty) {
          continue;
        }
        if (!ggGeneratedCommitMessages.contains(subject)) {
          return 'the repo contains the manual commit »$subject«';
        }
      }

      return null;
    } catch (e) {
      // A history that cannot be inspected cannot prove the repo unchanged.
      return 'the git history could not be inspected ($e)';
    }
  }

  // ...........................................................................
  /// The ref the feature branch is compared against — the remote main branch
  /// when available, the local one otherwise. Null when neither exists.
  Future<String?> _compareBase(Directory repoDir) async {
    const candidates = [
      'origin/main',
      'origin/master',
      'main',
      'master',
    ];
    for (final candidate in candidates) {
      final sha = await _runGit(
        <String>['rev-parse', '--verify', '--quiet', candidate],
        repoDir: repoDir,
        allowFailure: true,
      );
      if (sha.isNotEmpty) {
        return candidate;
      }
    }
    return null;
  }

  // ...........................................................................
  /// Runs git with [args] in [repoDir] and returns the trimmed stdout.
  Future<String> _runGit(
    List<String> args, {
    required Directory repoDir,
    bool allowFailure = false,
  }) =>
      runGit(
        _processRunner,
        args,
        repoDir: repoDir,
        allowFailure: allowFailure,
      );
}

/// Mock for [PublishSkipCheck]
class MockPublishSkipCheck extends Mock implements PublishSkipCheck {}
