// @license
// Copyright (c) 2019 - 2025 Dr. Gabriel Gatzsche. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:gg_multi/src/backend/dependency_overrides.dart';
import 'package:path/path.dart' as path;
import 'package:test/test.dart';

void main() {
  late Directory tempDir;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('dependency_overrides_test_');
  });

  tearDown(() {
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  Directory repo(String name, [String? overrides]) {
    final dir = Directory(path.join(tempDir.path, name))..createSync();
    if (overrides != null) {
      File(path.join(dir.path, pubspecOverridesFileName))
          .writeAsStringSync(overrides);
    }
    return dir;
  }

  String overridesOf(Directory dir) =>
      File(path.join(dir.path, pubspecOverridesFileName)).readAsStringSync();

  bool hasOverrides(Directory dir) =>
      File(path.join(dir.path, pubspecOverridesFileName)).existsSync();

  group('removeDependencyOverrides', () {
    test('removes the entry and keeps the remaining ones', () {
      final a = repo('a', '''
# Generated by gg_localize_refs.
dependency_overrides:
  b:
    path: ../b
  c:
    path: ../c
''');

      final changed = removeDependencyOverrides(
        repoDirs: [a],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      expect(overridesOf(a), contains('c:'));
      expect(overridesOf(a), isNot(contains('../b')));
      // The header comment of gg_localize_refs survives the edit.
      expect(overridesOf(a), contains('# Generated by gg_localize_refs.'));
    });

    test('deletes the file when nothing would be left to override', () {
      final a = repo('a', '''
dependency_overrides:
  b:
    path: ../b
''');

      final changed = removeDependencyOverrides(
        repoDirs: [a],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      expect(hasOverrides(a), isFalse);
    });

    test('touches only the repos that reference the removed package', () {
      final a = repo('a', 'dependency_overrides:\n  b:\n    path: ../b\n');
      final c = repo('c', 'dependency_overrides:\n  d:\n    path: ../d\n');

      final changed = removeDependencyOverrides(
        repoDirs: [a, c],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      expect(hasOverrides(c), isTrue);
    });

    test('returns nothing when no names are given', () {
      final a = repo('a', 'dependency_overrides:\n  b:\n    path: ../b\n');
      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: const {}),
        isEmpty,
      );
      expect(hasOverrides(a), isTrue);
    });

    test('skips a repo without pubspec_overrides.yaml', () {
      final a = repo('a');
      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: {'b'}),
        isEmpty,
      );
    });

    test('skips a file without a dependency_overrides map', () {
      final a = repo('a', 'dependency_overrides:\n');
      final b = repo('b', 'other: value\n');

      expect(
        removeDependencyOverrides(repoDirs: [a, b], packageNames: {'x'}),
        isEmpty,
      );
      expect(hasOverrides(a), isTrue);
      expect(hasOverrides(b), isTrue);
    });

    test('skips a file that is no YAML map', () {
      final a = repo('a', '- just\n- a list\n');
      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: {'b'}),
        isEmpty,
      );
      expect(hasOverrides(a), isTrue);
    });

    test('leaves an unparsable file alone', () {
      const broken = "dependency_overrides:\n  b: 'unterminated\n";
      final a = repo('a', broken);

      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: {'b'}),
        isEmpty,
      );
      expect(overridesOf(a), broken);
    });
  });
}
